### ISSUE TITLE
Investigate possibilties for extending vault policies to enable dynamic policices

### ISSUE THREAD

**Issue by simonswine** [jetstack/tarmak#120]
Currently we can't distinguish between, different instances of the same group #34. 

To achieve a separation between different instances we would need to dynamically generate policies that allow AWS instances get certificates for their FQDN.

Investigate our options:
- Implementing a controller loop that watches Vault's and/or EC2's API and creates the dynamic policies on the fly
- Is it possible to modify attached policies on an already created token
- Could this better be solved by a Tarmak Vault plugin, starting of with an fork of https://www.vaultproject.io/docs/auth/aws.html (we would use the EC2 way of authenticating)

To configure a full PKI like we do in tarmak, you can use https://github.com/jetstack/vault-helper/ and its `vault-helper devserver` subcommand

**Comment by simonswine** [comment]
@mt-inside

**Comment by mt-inside** [comment]
Hi!

**Comment by mt-inside** [comment]
Hey @JoshVanL, @simonswine  , sorry, I commented on the internal issue. Will reproduce here

**Comment by mt-inside** [comment]
Summary for w/b 5/3/18:
* I was very new to vault, so installed it, followed the intro guide (static secrets and policies etc)
* Got an AWS account, added root key, played with STS dynamic secrets
* Played with terraform vault provider breifly
* Got source, got vault building, testing and running locally

Blockers:
* Some time was lost to jetstack vault CSR signing
* Some time was lost to jetstack AWS sign-in and helpers (doesn't run on a fresh OS install, PR raised)

Next tasks:
* Run vault on EC2 instance, play with EC2 auth backend
* Write hello-world auth plugin
* See under what circumstances policies can be dynamically changed

**Comment by mt-inside** [comment]
Summary for w/b 12/3/18:
* Researched dynamic policy:
  * Policy names associated with a token can't be changed
  * Policy contents can
  * Vault Premium uses the Sentinel policy language, which looks like it could so what we want from a *static* policy (since it's so powerful)
  * There's a github issue asking for dynamic policies (with backreferences like web server routing rules), this was rejected as apparently it would need a lot of code refactoring
* Researched the AWS EC2 auth engine
  * There's a "role_tag" feature which seems to allow instances to drop some of the privileges their policy mapping would give them

Conclusion:
* Writing one policy expressive enough to do what we want doesn't seem possible and won't be added
* Policies can't be added to issued tokens, and EC2 role => policy mappings are static, so we can't add a per-instance policy after it auths, and we can't attach a new one to each instance and work the permissions out afterwards, because role_tag only lets you opt out of policy, not opt in.
* We _could_ try to write a controller that spots new instances before they try to login. We could add a cloud-init / systemd unit that blocks boot while the policy is made...
* Easiest method seems to be to write a custom EC2 authenticator, hopefully one that just makes the policy and then proxies through to the real one

Blockers:
* While researching I tried to get vault running in AWS but wanted it to be repeatable for testing or a possible move to an account where I have root. Hit loads of terraform / cloud-init problems doing this.

Next tasks:
* Get vault client and server running on AWS, authing to each other.
* Write hello-world auth plugin

**Comment by kragniz** [comment]
I've pulled out the vault awsauth backend and packaged it into a plugin to use as a base. I'm going to be testing it works properly and adding entry points for policy and role creation today.

**Comment by kragniz** [comment]
Dynamic role + policy vault plugin: https://github.com/jetstack/vault-plugin-auth-templated-aws

**Comment by simonswine** [comment]
Thanks @kragniz for looking into that
