### ISSUE TITLE
Lock down IAM roles

### ISSUE THREAD

**Issue by simonswine** [jetstack/tarmak#128]
/kind feature

We should lock down the AWS IAM permission further. Currently KOPS is doing a better job:

https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md

**Comment by mt-inside** [comment]
- At versions 1.8.8 and 1.9.6, clusters come up
  - Ingress ELBs show 0/3 healthy instances, but that's the same on master
- clusters comes down cleanly
- sonobouy passes
- service ELBs can be created and destroyed by Service[type=LB]
  - only 1/3 backing instances ever show healthy, but connections to Pods work fine
  - via Service annotations I have confirmed public ELBs, public NLBs, and internal ELBs. Connections checked from either an unrelated EC2 instance or "the internet"
- Dynamic PV provisioning works.
A default-storage-class PVC causes a PV to be made and bound, attachment to instances clearly works because the mount into the pod works, write access to the FS on the volume is OK, and detachment / unbinding / deletion is fine right back to thee EBS volume.
