### ISSUE TITLE
Release notes for 0.4.0

### ISSUE THREAD

**Issue by simonswine** [jetstack/tarmak#406]
We need to have good release notes for 0.4.0

I think main goals should be:
- Explain the terraform changes and how they will break compatablitly with pre 0.4 releases. Why we did that now and not thing we will do that later
- Mention the built in terraform vs. running in a container
- Terraform provider tarmak for ensuring the dependencies are working out
- Taints/Labels
- Logging
- Cluster Autoscaler

**Comment by dippynark** [comment]
The following sections detail changes of most note; they are not exhaustive list.

### Added
- Add Tarmak Terraform provider for ordering infrastructure creation (#12, @simonswine)
- Add support for automatically adding taints and labels to instance pools (#369, @charlieegan3)
- Support log forwarding (#197, @dippynark)
- Add Jenkins module to Terraform stack (#240, @MattiasGees)
- Support autoscaling arbitrary worker instance pools (#325, @dippynark)

### Changed
- Merged Terraform stacks (state, bastion, vault, network, kubernetes) into a single stack. This allows a plan to be run against all infrastructure at the same time and also benefit from Terraform's parallelisation  capabilities (#148, @dippynark)
- Vendored Terraform instead of shelling out to binary inside the Tarmak Docker container. This gives us more control over how terraform is run and the version used. Care must be take when running terraform commands within the Tarmak debug shell as using a version of Tarmak higher than the version vendored by Tarmak will prevent Tarmak from running further Terraform commands
- Change cgroup driver from systemd to cgroupfs as cgroupfs has better support in the kubelet for enforcing node allocatable (#300, @dippynark)

# Fixes
- Add security group to allow cluster autoscaler scaping (#338, @dippynark)
- Remove unneeded infrastructure (#329 #336 #321 @dippynark @MattiasGees)
- Pass through etcd instance pool min count to puppet (#322, @dippynark)
- Fix etcd mount race condition (#313, @dippynark)
- Add RBAC support to Dashboard (#343, @dippynark)
- Use correct versions for cluster autoscaler (#346, @dippynark)
- Return informative error when failing to parse tarmak configuration (#326, @dippynark)

```

**Comment by dippynark** [comment]
@simonswine ^

**Comment by simonswine** [comment]
@dippynark thanks!
