### ISSUE TITLE
Use Terraform to mount EBS volumes for Vault instances

### ISSUE THREAD

**Issue by dippynark** [jetstack/tarmak#482]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: Vault instances use the AWS CLI as part of a systemd unit to mount an external volume (https://github.com/jetstack/tarmak/blob/master/terraform/amazon/modules/vault/templates/vault_user_data.yaml). This should instead be managed by Terraform as with etcd instances

**Comment by dippynark** [comment]
This will be fixed by https://github.com/jetstack/tarmak/issues/93

**Comment by simonswine** [comment]
No it should not be attached using terraform, we need to mount from within the instance, otherwise we break the autorecover. Also terraform is not doing the unattachments reliably (this might be fixed though). Another issue is that this will affect targeting of a single instances out of `count > 1` resource.

I think we should use a golang binary to do the attachments/mounting/formating instead of AWS cli. But not too sure how big of an issue that is

**Comment by dippynark** [comment]
@simonswine how does it break autorecover? You can specify the index you are targetting so that wouldn't be an issue afaik

**Comment by simonswine** [comment]
autorecover is the feature where AWS is recreating the instance that just died. There is no one around to attach a custom EBS volume to it

Targeting doesn't make to much sense in that case (that sounds like terraform targeting to me)
