### ISSUE TITLE
kdump.service & network.service failing

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/tarmak#557]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
(perhaps?)

**What happened**:
I recently created a new Tarmak cluster in response to support ticket. The customer referenced the failing kdump and network services.

These were unrelated to the issue but they had caused confusion.

On my nodes the kdump and network were failing as follows:

| node    | kdump   | network |
|---------|---------|---------|
| master  |         | failing |
| vault   | failing | failing |
| worker  |         | failing |
| etcd    |         | failing |
| bastion | failing | failing |

**What you expected to happen**:
When a node is healthy, for it to have no failing systemd units so as not to distract from other issues.

**How to reproduce it (as minimally and precisely as possible)**:
I have seen this on other, if not most clusters I've worked on before but have never looked into the cause.

**Comment by charlieegan3** [comment]
The kdump failure is likely caused by selinux. The network failure is present on the stock ami and is related to the AWS networking.

Best fix at the moment is likely to disable these units while they're causing red-herrings while debugging other issues.

**Comment by simonswine** [comment]
I think we need to integrate that into tarmak image build

```
rm /etc/sysconfig/network-scripts/ifcfg-ens*
```
To fix the network. 

I am having to getting the kdump to work. I suggest we are disabling it using `systemctl disable kdump` during the tarmak image build

**Comment by wallrj** [comment]
* https://github.com/jetstack/katacoda-scenarios/pull/75 has some information about kdump service. I've disabled it there, but it may be a useful service to enable in a production tarmak environment....and it may just require you specifying a fixed `crashkernel=X` because `auto` sometimes gets it wrong and chooses `0`.
* Here's a Packer script which disables crashkernel and disables new style network interface names: https://github.com/jetstack/katacoda-scenarios/blob/1c7f95090263c08a3e02bc30852ece93c928c7e8/environments/kubernetes/provisioner_scripts/00-networking.sh

**Comment by simonswine** [comment]
The problem related to kdump is more that we don't run the upstream kernel in all cases. And there is no support in non Red Hat kernel for those. On the upstream kernel the non zero helps indeed. But I think I would question the value provided.

Regarding the device names it's more that we have a different device name in the packer build than in the actual image later, as we are disabling the vendor specific device names as you do in the katacoda scenarios
